import 'package:flutter/material.dart';
import './meal.dart';
import './category.dart';

const DUMMY_CATEGORIES = const[
  Category(
    id: 'c1',
    title: 'Quick and easy',
    color: Colors.purple,
  ),
  Category(
    id: 'c2',
    title: 'Calabar',
    color: Colors.red,
  ),
  Category(
    id: 'c3',
    title: 'Hausa',
    color: Colors.orange,
  ),
  Category(
    id: 'c4',
    title: 'Ekiti',
    color: Colors.amber,
  ),
  Category(
    id: 'c5',
    title: 'Light and lovely',
    color: Colors.blue,
  ),
  Category(
    id: 'c6',
    title: 'Exotic',
    color: Colors.green,
  ),
  Category(
    id: 'c7',
    title: 'Breakfast',
    color: Colors.lightBlue,
  ),
  Category(
    id: 'c8',
    title: 'Oyo',
    color: Colors.lightGreen,
  ),
  Category(
    id: 'c9',
    title: 'Snacks',
    color: Colors.pink,
  ),
  Category(
    id: 'c10',
    title: 'Igbo',
    color: Colors.teal,
  ),
];

const DUMMY_MEALS = const[
 Meal(
   id: 'm1',
   categories: [
     'c1',
     'c2',
   ],
   title: 'Spaghetti with tomato sauce',
   affordability: Affordability.Pricey,
   complexity: Complexity.Simple,
   imageUrl: 'https://www.google.com/imgres?imgurl=https%3A%2F%2Fwww.giallozafferano.com%2Fimages%2F228-22832%2Fspaghetti-with-tomato-sauce_1200x800.jpg&imgrefurl=https%3A%2F%2Fwww.giallozafferano.com%2Frecipes%2Fspaghetti-with-tomato-sauce.html&tbnid=BW5YALzhkQxxgM&vet=12ahUKEwjbvqGd_oHzAhVSZhQKHZEICLMQMygHegUIARDtAQ..i&docid=PlATZW9zGVpaHM&w=1200&h=800&q=spaghetti%20with%20tomato%20sauce%20recipe&ved=2ahUKEwjbvqGd_oHzAhVSZhQKHZEICLMQMygHegUIARDtAQ',
   duration: 20,
   ingredients: [
     '4 tomatoes',
     '1 tablespoon of olive oil',
     '1 onion',
     '250g Spaghetti',
     'Spices',
     'cheese (optional)'
   ],
   isGlutenFree: false,
   isVegan: false,
   isVegetarian: false,
   isLactoseFree: true,
 ),
    Meal(
id: 'm2',
categories: [
'c3',
'c4',
],
title: 'Abak Atama',
affordability: Affordability.Affordable,
complexity: Complexity.Challenging,
imageUrl: 'https://www.allnigerianrecipes.com/wp-content/uploads/2019/04/abak-atama-soup.jpg',
duration: 20,
ingredients: [
  '500g Palm Fruits or 400g tinned Palm Fruit',
  'Assorted meat and fish',
  'Beef or Goat Meat',
  'Cow Skin (ponmo)',
  'Smoked fish',
  'Dry fish',
  'Stock fish',
  '1 handful thinly sliced atama leaves',
  '1 onion',
  '2 tablespoons ground crayfish',
  '2 milk cups unshelled periwinkles',
  'Habanero pepper (Atarodo, ose oyibo, atarugu: to taste)',
  '2 small stock cubes',
  'Salt (to taste)',
],
isGlutenFree: false,
isVegan: false,
isVegetarian: false,
isLactoseFree: true,
    ),
  Meal(
    id: 'm3',
    categories: [
      'c5',
      'c6',
    ],
    title: 'Tuwo Skinkafa',
    affordability: Affordability.Affordable,
    complexity: Complexity.Challenging,
    imageUrl: 'https://www.nigerianfoodtv.com/ezoimgfmt/2.bp.blogspot.com/-8HmcEx5oXGA/U4hZsPXWtoI/AAAAAAAADEw/2l_VuIIzqa0/s1600/tuwo+shinkafa.JPG?ezimgfmt=rs:690x501/rscb6/ng:webp/ngcb6',
    duration: 20,
    ingredients: [
      '500 grams Short grain rice or local rice (paella rice can be used as a substitute)',
       '1000ml(1L) water (more or less)',
    ],
    isGlutenFree: false,
    isVegan: false,
    isVegetarian: false,
    isLactoseFree: true,
  ),
  Meal(
    id: 'm4',
    categories: [
      'c7',
      'c8',
    ],
    title: 'Iyan and eforiro',
    affordability: Affordability.Affordable,
    complexity: Complexity.Hard,
    imageUrl: 'https://allnigerianfoods.com/wp-content/uploads/2015/03/efo-riro.jpg',
    duration: 20,
    ingredients: [
      'Sliced Spinach leaves (7-10 cups)',
      '7-10 pieces stock fish ear',
      'assorted meat (1KG)',
      '1 cup of sliced/ground tatashe',
      'quater cup of sliced pepper',
      'half cup of sliced onions',
      'Half Cup of Ground Crayfish',
      '2-3 spoons of iru (locust beans)',
      'smoked fish (2-3 medium)',
      'Palm oil (200ml)',
      '3 Seasoning cubes',
    ],
    isGlutenFree: false,
    isVegan: false,
    isVegetarian: false,
    isLactoseFree: true,
  ),
  Meal(
    id: 'm5',
    categories: [
      'c9',
      'c10',
    ],
    title: 'Noodles',
    affordability: Affordability.Affordable,
    complexity: Complexity.Simple,
    imageUrl: 'https://static.toiimg.com/photo/52467119.cms',
    duration: 20,
    ingredients: [
      '250 gm parboiled fresh noodles',
      '1 cup chopped,grated cabbage',
      '1 cup sliced onion',
      '2 teaspoon powdered black pepper',
      '2 tablespoon sunflower oil',
      '3 teaspoon garlic paste',
      '1 cup finely chopped bean',
      '3 eggs',
      '1 cup grated carrot',
      '7 sliced green chilli',
      'salt as required',
      '3 teaspoon ginger paste',
      '1 teaspoon ajinomoto',
      '2 tablespoon soy sauce',
    ],
    isGlutenFree: false,
    isVegan: false,
    isVegetarian: false,
    isLactoseFree: true,
  ),
  Meal(
    id: 'm6',
    categories: [
      'c4',
      'c7',
    ],
    title: 'Chapman',
    affordability: Affordability.Luxurious,
    complexity: Complexity.Simple,
    imageUrl: 'https://www.mydiasporakitchen.com/wp-content/uploads/2018/12/savingpng-165-1.png',
    duration: 20,
    ingredients: [
  '2 types of carbonated drinks; orange drink like Fanta, Crush etc. and a clear carbonated drink like seven up or sprite',
  'Some cucumber slices',
  'Lime or lemon slices',
  'Angostura bitters',
  'Grenadine syrup',
  'Black Currant drink like Ribena or Zobo concentrate ( optional)',
    ],
    isGlutenFree: false,
    isVegan: false,
    isVegetarian: false,
    isLactoseFree: true,
  ),
  Meal(
    id: 'm7',
    categories: [
      'c6',
      'c9',
    ],
    title: 'Bread and Tea',
    affordability: Affordability.Affordable,
    complexity: Complexity.Simple,
    imageUrl: 'https://img-global.cpcdn.com/recipes/e4f6be1623969d5c/680x482cq70/toasted-bread-and-tea-recipe-main-photo.webp',
    duration: 20,
    ingredients: [
      '10 sliced bread',
      '2 eggs',
      '1 tbsp butter',
    ],
    isGlutenFree: false,
    isVegan: false,
    isVegetarian: false,
    isLactoseFree: true,
  ),
  Meal(
    id: 'm8',
    categories: [
      'c7',
      'c10',
    ],
    title: 'Amala and ewedu',
    affordability: Affordability.Affordable,
    complexity: Complexity.Challenging,
    imageUrl: 'https://img-global.cpcdn.com/recipes/3a179db19504dd1e/640x640sq70/photo.webp',
    duration: 20,
    ingredients: [
      'Ewedu leave',
      'Local broom',
      'Locust beans',
      'Salt',
      'Water',
      'Potash',
      '1 Maggi cube',
      'Stew',
    ],
    isGlutenFree: false,
    isVegan: false,
    isVegetarian: false,
    isLactoseFree: true,
  ),
  Meal(
    id: 'm9',
    categories: [
      'c3',
      'c6',
    ],
    title: 'Doughnut',
    affordability: Affordability.Affordable,
    complexity: Complexity.Simple,
    imageUrl: 'https://letthebakingbegin.com/wp-content/uploads/2013/11/Simple-Homemade-Sugar-Donuts-are-super-easy-to-make-and-are-so-so-delicious-Theyre-fluffy-soft-and-taste-much-better-than-any-bakery-donut.-1-7-600x900.jpg',
    duration: 20,
    ingredients: [
  'flour',
      'sugar',
      'water',
      'yeast',
    ],
    isGlutenFree: false,
    isVegan: false,
    isVegetarian: false,
    isLactoseFree: true,
  ),
  Meal(
    id: 'm10',
    categories: [
      'c2',
      'c10',
    ],
    title: 'Akpu and Ogbono',
    affordability: Affordability.Affordable,
    complexity: Complexity.Hard,
    imageUrl: 'https://img-global.cpcdn.com/recipes/52781cf2b94de7ef/680x482cq70/ogbonor-soup-and-akpu-recipe-main-photo.webp',
    duration: 20,
    ingredients: [
      'Ogbonor',
      'Beef',
      'Dry fish',
      'Crayfish',
      'Onion',
      'cubes Seasoning',
      'Fresh pepper',
      'leaf Pumkpin/ugu',
      'Palm oil',
      'Salt',
    ],
    isGlutenFree: false,
    isVegan: false,
    isVegetarian: false,
    isLactoseFree: true,
  ),
];